export const themes = {
    // night: {
    //     pageBackGroundGradientTopLeft: '#111217',
    //     pageBackGroundGradientBottomRight: '#141739',
    //     menuBackGroundGradientTopLeft: '#0D0D0D',
    //     menuBackGroundGradientBottomRight: '#07061B',
    //     mainCategoriesBackground: '#1E2242',
    //     headerMenuActiveItem: '#F3F8FF',
    //     headerMenuActiveText: '#313131',
    //     searchBackground: '#373535',
    //     searchColor: '#A5A5A5',
    //     buttons: '#F3215E',
    //     hotLinks:'#F3215E',
    //     buttonBarBackground: '#0E0F11',
    //     studioAndMeMenuButtons: '#1D335B',
    //     inputFields: '#1D335B',
    //     activityFeedBoxesGradientTopLeft: '#151a32',
    //     activityFeedBoxesGradientBottomRight: '#1b2244',
    //     colorFont: '#fff',
    //     colorFontGrey: 'rgba(255, 255, 255, 0.6)',
    //     creatorCardLeft: '#0D0D0D',
    //     creatorCardRight: '#07061B',
    //     invert: '1',
    //     bgSectionHomeTopLeft: '#0D0D0D',
    //     bgSectionHomeBottomRight: '#07061B',
    //     liveChatEventsTop: '#0D0D0D',
    //     liveChatEventsBottom: '#07061B',
    // },
    // vivid: {
    //     pageBackGroundGradientTopLeft: '#251157',
    //     pageBackGroundGradientBottomRight: '#592057',
    //     menuBackGroundGradientTopLeft: '#1A103A',
    //     menuBackGroundGradientBottomRight: '#25143A',
    //     mainCategoriesBackground: '#1E2242',
    //     headerMenuActiveItem: '#F3F8FF',
    //     headerMenuActiveText: '#313131',
    //     searchBackground: '#373535',
    //     searchColor: '#A5A5A5',
    //     buttons: '#F3215E',
    //     hotLinks:'#F3215E',
    //     buttonBarBackground: '#0E0F11',
    //     studioAndMeMenuButtons: '#1C0345',
    //     inputFields: '#1C0345',
    //     activityFeedBoxesGradientTopLeft: '#151a32',
    //     activityFeedBoxesGradientBottomRight: '#1b2244',
    //     colorFont: '#fff',
    //     colorFontGrey: 'rgba(255, 255, 255, 0.6)',
    //     creatorCardLeft: '#1A103A',
    //     creatorCardRight: '#25143A',
    //     invert: '1',
    //     bgSectionHomeTopLeft: '#1A103A',
    //     bgSectionHomeBottomRight: '#25143A',
    //     liveChatEventsTop: '#0D0D0D',
    //     liveChatEventsBottom: '#07061B',
    // },
    // midnigth: {
    //     pageBackGroundGradientTopLeft: '#000000',
    //     pageBackGroundGradientBottomRight: '#0C0C0C',
    //     menuBackGroundGradientTopLeft: '#100F0F',
    //     menuBackGroundGradientBottomRight: '#100F0F',
    //     mainCategoriesBackground: '#1A1A1A',
    //     headerMenuActiveItem: '#F3F8FF',
    //     headerMenuActiveText: '#313131',
    //     searchBackground: '#373535',
    //     searchColor: '#A5A5A5',
    //     buttons: '#F3215E',
    //     hotLinks:'#F3215E',
    //     buttonBarBackground: '#0E0F11',
    //     studioAndMeMenuButtons: '#2D2828',
    //     inputFields: '#2D2828',
    //     activityFeedBoxesGradientTopLeft: '#121212',
    //     activityFeedBoxesGradientBottomRight: '#100F0F',
    //     colorFont: '#fff',
    //     colorFontGrey: 'rgba(255, 255, 255, 0.6)',
    //     creatorCardLeft: '#100F0F',
    //     creatorCardRight: '#100F0F',
    //     invert: '1',
    //     bgSectionHomeTopLeft: '#100F0F',
    //     bgSectionHomeBottomRight: '#100F0F',
    //     liveChatEventsTop: '#1A1A1A',
    //     liveChatEventsBottom: '#1A1A1A',
    // },
    daylight: {
        pageBackGroundGradientTopLeft: '#F0F2F5',
        pageBackGroundGradientBottomRight: '#F0F2F5',
        menuBackGroundGradientTopLeft: ' rgba(255, 255, 255, 0.7)',
        menuBackGroundGradientBottomRight: ' rgba(255, 255, 255, 0.7)',
        mainCategoriesBackground: '#000000',
        headerMenuActiveItem: '#F3F8FF',
        headerMenuActiveText: '#313131',
        searchBackground: '#F7F7F7',
        searchColor: '#A5A5A5',
        buttons: '#c248fc',
        hotLinks:'#c248fc',
        buttonBarBackground: '#0E0F11',
        studioAndMeMenuButtons: '#FFFFFF',
        inputFields: '#FFFFFF',
        activityFeedBoxesGradientTopLeft: '#FFFFFF',
        activityFeedBoxesGradientBottomRight: '#FFFFFF',
        colorFont: '#000000',
        colorFontGrey: '#8898aa',
        creatorCardLeft: '#fff',
        creatorCardRight: '#fff',
        invert: '0',
        bgSectionHomeTopLeft: '#F0F2F5',
        bgSectionHomeBottomRight: '#F0F2F5',
        liveChatEventsTop: '#000000',
        liveChatEventsBottom: '#000000',
        menuCategoriesHome: '#F9F9FA',

    }
}